### ISSUE TITLE
[Bug/Crash] Rapidly changing songs causes a crash

### ISSUE THREAD

**Issue by KabanFriends** [digimezzo/dopamine#722]
When you quickly switch songs in the latest version of the app, the music becomes glitched for a few seconds before the app crashes.

Version: 3.0.0-preview.35
Log: [Dopamine.log](https://github.com/user-attachments/files/17607031/Dopamine.log) (File names have been edited to hide the actual songs)

**Comment by digimezzo** [comment]
@KabanFriends Could you try out this build? https://github.com/digimezzo/dopamine/actions/runs/11619031390
It should fix the crash issue.

**Comment by KabanFriends** [comment]
Playaback seems to be less glitchy (aside from a very little stuttering right after the start of the song) but the app still crashed after switching songs a few times.

Log: [Dopamine.log](https://github.com/user-attachments/files/17609293/Dopamine.log)
